spring:
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME:mini_project_data_jpa}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true